server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true #because of this I can set "ACCOUNTS" to "accounts" and same for other services
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "BanklyCore gateway Server Application"
    version: "1.0.0"


logging:
  level:
    com:
      example:
        gatewayserver: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"



resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10   # this tells to make at try 10 request before going from closed to open circuit
      permittedNumberOfCallsInHalfOpenState: 2  # I want my circuit breaker pattern to try 2 request in the half open circuit state based on  response it will decide what to do whether go to closed state or go to full open state
      failureRateThreshold: 50  # if ate least 50 percent of the request are failed then move to open circuit state
      waitDurationInOpenState: 10000 # 10 sec